// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.microservice.hub;

public final class Bank {
  private Bank() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.microservice.hub.FileData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>bytes fileContent = 2;</code>
     * @return The fileContent.
     */
    com.google.protobuf.ByteString getFileContent();
  }
  /**
   * Protobuf type {@code com.microservice.hub.FileData}
   */
  public static final class FileData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.microservice.hub.FileData)
      FileDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileData.newBuilder() to construct.
    private FileData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileData() {
      fileName_ = "";
      fileContent_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservice.hub.Bank.internal_static_com_microservice_hub_FileData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservice.hub.Bank.internal_static_com_microservice_hub_FileData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservice.hub.Bank.FileData.class, com.microservice.hub.Bank.FileData.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileName_ = "";
    /**
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILECONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString fileContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes fileContent = 2;</code>
     * @return The fileContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFileContent() {
      return fileContent_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      if (!fileContent_.isEmpty()) {
        output.writeBytes(2, fileContent_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      if (!fileContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, fileContent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microservice.hub.Bank.FileData)) {
        return super.equals(obj);
      }
      com.microservice.hub.Bank.FileData other = (com.microservice.hub.Bank.FileData) obj;

      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!getFileContent()
          .equals(other.getFileContent())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getFileContent().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microservice.hub.Bank.FileData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.FileData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.FileData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.FileData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.FileData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.FileData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.FileData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservice.hub.Bank.FileData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.microservice.hub.Bank.FileData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.microservice.hub.Bank.FileData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microservice.hub.Bank.FileData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservice.hub.Bank.FileData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microservice.hub.Bank.FileData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.microservice.hub.FileData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.microservice.hub.FileData)
        com.microservice.hub.Bank.FileDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_FileData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_FileData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microservice.hub.Bank.FileData.class, com.microservice.hub.Bank.FileData.Builder.class);
      }

      // Construct using com.microservice.hub.Bank.FileData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fileName_ = "";
        fileContent_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_FileData_descriptor;
      }

      @java.lang.Override
      public com.microservice.hub.Bank.FileData getDefaultInstanceForType() {
        return com.microservice.hub.Bank.FileData.getDefaultInstance();
      }

      @java.lang.Override
      public com.microservice.hub.Bank.FileData build() {
        com.microservice.hub.Bank.FileData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.microservice.hub.Bank.FileData buildPartial() {
        com.microservice.hub.Bank.FileData result = new com.microservice.hub.Bank.FileData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.microservice.hub.Bank.FileData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fileName_ = fileName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fileContent_ = fileContent_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microservice.hub.Bank.FileData) {
          return mergeFrom((com.microservice.hub.Bank.FileData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microservice.hub.Bank.FileData other) {
        if (other == com.microservice.hub.Bank.FileData.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getFileContent() != com.google.protobuf.ByteString.EMPTY) {
          setFileContent(other.getFileContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fileName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                fileContent_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 1;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 1;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 1;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        fileName_ = getDefaultInstance().getFileName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 1;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString fileContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes fileContent = 2;</code>
       * @return The fileContent.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getFileContent() {
        return fileContent_;
      }
      /**
       * <code>bytes fileContent = 2;</code>
       * @param value The fileContent to set.
       * @return This builder for chaining.
       */
      public Builder setFileContent(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        fileContent_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes fileContent = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileContent_ = getDefaultInstance().getFileContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.microservice.hub.FileData)
    }

    // @@protoc_insertion_point(class_scope:com.microservice.hub.FileData)
    private static final com.microservice.hub.Bank.FileData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microservice.hub.Bank.FileData();
    }

    public static com.microservice.hub.Bank.FileData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileData>
        PARSER = new com.google.protobuf.AbstractParser<FileData>() {
      @java.lang.Override
      public FileData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FileData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.microservice.hub.Bank.FileData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BankInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.microservice.hub.BankInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string bankId = 1;</code>
     * @return The bankId.
     */
    java.lang.String getBankId();
    /**
     * <code>string bankId = 1;</code>
     * @return The bytes for bankId.
     */
    com.google.protobuf.ByteString
        getBankIdBytes();

    /**
     * <code>string bankHostname = 2;</code>
     * @return The bankHostname.
     */
    java.lang.String getBankHostname();
    /**
     * <code>string bankHostname = 2;</code>
     * @return The bytes for bankHostname.
     */
    com.google.protobuf.ByteString
        getBankHostnameBytes();

    /**
     * <code>int32 bankPort = 3;</code>
     * @return The bankPort.
     */
    int getBankPort();
  }
  /**
   * Protobuf type {@code com.microservice.hub.BankInfo}
   */
  public static final class BankInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.microservice.hub.BankInfo)
      BankInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BankInfo.newBuilder() to construct.
    private BankInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BankInfo() {
      bankId_ = "";
      bankHostname_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BankInfo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservice.hub.Bank.internal_static_com_microservice_hub_BankInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservice.hub.Bank.internal_static_com_microservice_hub_BankInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservice.hub.Bank.BankInfo.class, com.microservice.hub.Bank.BankInfo.Builder.class);
    }

    public static final int BANKID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bankId_ = "";
    /**
     * <code>string bankId = 1;</code>
     * @return The bankId.
     */
    @java.lang.Override
    public java.lang.String getBankId() {
      java.lang.Object ref = bankId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bankId_ = s;
        return s;
      }
    }
    /**
     * <code>string bankId = 1;</code>
     * @return The bytes for bankId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBankIdBytes() {
      java.lang.Object ref = bankId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bankId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BANKHOSTNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bankHostname_ = "";
    /**
     * <code>string bankHostname = 2;</code>
     * @return The bankHostname.
     */
    @java.lang.Override
    public java.lang.String getBankHostname() {
      java.lang.Object ref = bankHostname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bankHostname_ = s;
        return s;
      }
    }
    /**
     * <code>string bankHostname = 2;</code>
     * @return The bytes for bankHostname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBankHostnameBytes() {
      java.lang.Object ref = bankHostname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bankHostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BANKPORT_FIELD_NUMBER = 3;
    private int bankPort_ = 0;
    /**
     * <code>int32 bankPort = 3;</code>
     * @return The bankPort.
     */
    @java.lang.Override
    public int getBankPort() {
      return bankPort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bankId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bankId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bankHostname_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bankHostname_);
      }
      if (bankPort_ != 0) {
        output.writeInt32(3, bankPort_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bankId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bankId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bankHostname_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bankHostname_);
      }
      if (bankPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, bankPort_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microservice.hub.Bank.BankInfo)) {
        return super.equals(obj);
      }
      com.microservice.hub.Bank.BankInfo other = (com.microservice.hub.Bank.BankInfo) obj;

      if (!getBankId()
          .equals(other.getBankId())) return false;
      if (!getBankHostname()
          .equals(other.getBankHostname())) return false;
      if (getBankPort()
          != other.getBankPort()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BANKID_FIELD_NUMBER;
      hash = (53 * hash) + getBankId().hashCode();
      hash = (37 * hash) + BANKHOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getBankHostname().hashCode();
      hash = (37 * hash) + BANKPORT_FIELD_NUMBER;
      hash = (53 * hash) + getBankPort();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microservice.hub.Bank.BankInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.BankInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.BankInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.BankInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.BankInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.BankInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.BankInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservice.hub.Bank.BankInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.microservice.hub.Bank.BankInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.microservice.hub.Bank.BankInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microservice.hub.Bank.BankInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservice.hub.Bank.BankInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microservice.hub.Bank.BankInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.microservice.hub.BankInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.microservice.hub.BankInfo)
        com.microservice.hub.Bank.BankInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_BankInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_BankInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microservice.hub.Bank.BankInfo.class, com.microservice.hub.Bank.BankInfo.Builder.class);
      }

      // Construct using com.microservice.hub.Bank.BankInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bankId_ = "";
        bankHostname_ = "";
        bankPort_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_BankInfo_descriptor;
      }

      @java.lang.Override
      public com.microservice.hub.Bank.BankInfo getDefaultInstanceForType() {
        return com.microservice.hub.Bank.BankInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.microservice.hub.Bank.BankInfo build() {
        com.microservice.hub.Bank.BankInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.microservice.hub.Bank.BankInfo buildPartial() {
        com.microservice.hub.Bank.BankInfo result = new com.microservice.hub.Bank.BankInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.microservice.hub.Bank.BankInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bankId_ = bankId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bankHostname_ = bankHostname_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.bankPort_ = bankPort_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microservice.hub.Bank.BankInfo) {
          return mergeFrom((com.microservice.hub.Bank.BankInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microservice.hub.Bank.BankInfo other) {
        if (other == com.microservice.hub.Bank.BankInfo.getDefaultInstance()) return this;
        if (!other.getBankId().isEmpty()) {
          bankId_ = other.bankId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getBankHostname().isEmpty()) {
          bankHostname_ = other.bankHostname_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getBankPort() != 0) {
          setBankPort(other.getBankPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                bankId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                bankHostname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                bankPort_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object bankId_ = "";
      /**
       * <code>string bankId = 1;</code>
       * @return The bankId.
       */
      public java.lang.String getBankId() {
        java.lang.Object ref = bankId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bankId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bankId = 1;</code>
       * @return The bytes for bankId.
       */
      public com.google.protobuf.ByteString
          getBankIdBytes() {
        java.lang.Object ref = bankId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bankId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bankId = 1;</code>
       * @param value The bankId to set.
       * @return This builder for chaining.
       */
      public Builder setBankId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bankId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string bankId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBankId() {
        bankId_ = getDefaultInstance().getBankId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string bankId = 1;</code>
       * @param value The bytes for bankId to set.
       * @return This builder for chaining.
       */
      public Builder setBankIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bankId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object bankHostname_ = "";
      /**
       * <code>string bankHostname = 2;</code>
       * @return The bankHostname.
       */
      public java.lang.String getBankHostname() {
        java.lang.Object ref = bankHostname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bankHostname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bankHostname = 2;</code>
       * @return The bytes for bankHostname.
       */
      public com.google.protobuf.ByteString
          getBankHostnameBytes() {
        java.lang.Object ref = bankHostname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bankHostname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bankHostname = 2;</code>
       * @param value The bankHostname to set.
       * @return This builder for chaining.
       */
      public Builder setBankHostname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bankHostname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string bankHostname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBankHostname() {
        bankHostname_ = getDefaultInstance().getBankHostname();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string bankHostname = 2;</code>
       * @param value The bytes for bankHostname to set.
       * @return This builder for chaining.
       */
      public Builder setBankHostnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bankHostname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int bankPort_ ;
      /**
       * <code>int32 bankPort = 3;</code>
       * @return The bankPort.
       */
      @java.lang.Override
      public int getBankPort() {
        return bankPort_;
      }
      /**
       * <code>int32 bankPort = 3;</code>
       * @param value The bankPort to set.
       * @return This builder for chaining.
       */
      public Builder setBankPort(int value) {

        bankPort_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bankPort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBankPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bankPort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.microservice.hub.BankInfo)
    }

    // @@protoc_insertion_point(class_scope:com.microservice.hub.BankInfo)
    private static final com.microservice.hub.Bank.BankInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microservice.hub.Bank.BankInfo();
    }

    public static com.microservice.hub.Bank.BankInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BankInfo>
        PARSER = new com.google.protobuf.AbstractParser<BankInfo>() {
      @java.lang.Override
      public BankInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BankInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BankInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.microservice.hub.Bank.BankInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PushFileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.microservice.hub.PushFileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string bankId = 1;</code>
     * @return The bankId.
     */
    java.lang.String getBankId();
    /**
     * <code>string bankId = 1;</code>
     * @return The bytes for bankId.
     */
    com.google.protobuf.ByteString
        getBankIdBytes();

    /**
     * <code>.com.microservice.hub.FileData fileData = 2;</code>
     * @return Whether the fileData field is set.
     */
    boolean hasFileData();
    /**
     * <code>.com.microservice.hub.FileData fileData = 2;</code>
     * @return The fileData.
     */
    com.microservice.hub.Bank.FileData getFileData();
    /**
     * <code>.com.microservice.hub.FileData fileData = 2;</code>
     */
    com.microservice.hub.Bank.FileDataOrBuilder getFileDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.microservice.hub.PushFileRequest}
   */
  public static final class PushFileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.microservice.hub.PushFileRequest)
      PushFileRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PushFileRequest.newBuilder() to construct.
    private PushFileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushFileRequest() {
      bankId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PushFileRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservice.hub.Bank.internal_static_com_microservice_hub_PushFileRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservice.hub.Bank.internal_static_com_microservice_hub_PushFileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservice.hub.Bank.PushFileRequest.class, com.microservice.hub.Bank.PushFileRequest.Builder.class);
    }

    public static final int BANKID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bankId_ = "";
    /**
     * <code>string bankId = 1;</code>
     * @return The bankId.
     */
    @java.lang.Override
    public java.lang.String getBankId() {
      java.lang.Object ref = bankId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bankId_ = s;
        return s;
      }
    }
    /**
     * <code>string bankId = 1;</code>
     * @return The bytes for bankId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBankIdBytes() {
      java.lang.Object ref = bankId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bankId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILEDATA_FIELD_NUMBER = 2;
    private com.microservice.hub.Bank.FileData fileData_;
    /**
     * <code>.com.microservice.hub.FileData fileData = 2;</code>
     * @return Whether the fileData field is set.
     */
    @java.lang.Override
    public boolean hasFileData() {
      return fileData_ != null;
    }
    /**
     * <code>.com.microservice.hub.FileData fileData = 2;</code>
     * @return The fileData.
     */
    @java.lang.Override
    public com.microservice.hub.Bank.FileData getFileData() {
      return fileData_ == null ? com.microservice.hub.Bank.FileData.getDefaultInstance() : fileData_;
    }
    /**
     * <code>.com.microservice.hub.FileData fileData = 2;</code>
     */
    @java.lang.Override
    public com.microservice.hub.Bank.FileDataOrBuilder getFileDataOrBuilder() {
      return fileData_ == null ? com.microservice.hub.Bank.FileData.getDefaultInstance() : fileData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bankId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bankId_);
      }
      if (fileData_ != null) {
        output.writeMessage(2, getFileData());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bankId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bankId_);
      }
      if (fileData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFileData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microservice.hub.Bank.PushFileRequest)) {
        return super.equals(obj);
      }
      com.microservice.hub.Bank.PushFileRequest other = (com.microservice.hub.Bank.PushFileRequest) obj;

      if (!getBankId()
          .equals(other.getBankId())) return false;
      if (hasFileData() != other.hasFileData()) return false;
      if (hasFileData()) {
        if (!getFileData()
            .equals(other.getFileData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BANKID_FIELD_NUMBER;
      hash = (53 * hash) + getBankId().hashCode();
      if (hasFileData()) {
        hash = (37 * hash) + FILEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getFileData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microservice.hub.Bank.PushFileRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.PushFileRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.PushFileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.PushFileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.PushFileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.PushFileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.PushFileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservice.hub.Bank.PushFileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.microservice.hub.Bank.PushFileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.microservice.hub.Bank.PushFileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microservice.hub.Bank.PushFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservice.hub.Bank.PushFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microservice.hub.Bank.PushFileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.microservice.hub.PushFileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.microservice.hub.PushFileRequest)
        com.microservice.hub.Bank.PushFileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_PushFileRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_PushFileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microservice.hub.Bank.PushFileRequest.class, com.microservice.hub.Bank.PushFileRequest.Builder.class);
      }

      // Construct using com.microservice.hub.Bank.PushFileRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bankId_ = "";
        fileData_ = null;
        if (fileDataBuilder_ != null) {
          fileDataBuilder_.dispose();
          fileDataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_PushFileRequest_descriptor;
      }

      @java.lang.Override
      public com.microservice.hub.Bank.PushFileRequest getDefaultInstanceForType() {
        return com.microservice.hub.Bank.PushFileRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.microservice.hub.Bank.PushFileRequest build() {
        com.microservice.hub.Bank.PushFileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.microservice.hub.Bank.PushFileRequest buildPartial() {
        com.microservice.hub.Bank.PushFileRequest result = new com.microservice.hub.Bank.PushFileRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.microservice.hub.Bank.PushFileRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bankId_ = bankId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fileData_ = fileDataBuilder_ == null
              ? fileData_
              : fileDataBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microservice.hub.Bank.PushFileRequest) {
          return mergeFrom((com.microservice.hub.Bank.PushFileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microservice.hub.Bank.PushFileRequest other) {
        if (other == com.microservice.hub.Bank.PushFileRequest.getDefaultInstance()) return this;
        if (!other.getBankId().isEmpty()) {
          bankId_ = other.bankId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasFileData()) {
          mergeFileData(other.getFileData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                bankId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getFileDataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object bankId_ = "";
      /**
       * <code>string bankId = 1;</code>
       * @return The bankId.
       */
      public java.lang.String getBankId() {
        java.lang.Object ref = bankId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bankId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bankId = 1;</code>
       * @return The bytes for bankId.
       */
      public com.google.protobuf.ByteString
          getBankIdBytes() {
        java.lang.Object ref = bankId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bankId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bankId = 1;</code>
       * @param value The bankId to set.
       * @return This builder for chaining.
       */
      public Builder setBankId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bankId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string bankId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBankId() {
        bankId_ = getDefaultInstance().getBankId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string bankId = 1;</code>
       * @param value The bytes for bankId to set.
       * @return This builder for chaining.
       */
      public Builder setBankIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bankId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.microservice.hub.Bank.FileData fileData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.microservice.hub.Bank.FileData, com.microservice.hub.Bank.FileData.Builder, com.microservice.hub.Bank.FileDataOrBuilder> fileDataBuilder_;
      /**
       * <code>.com.microservice.hub.FileData fileData = 2;</code>
       * @return Whether the fileData field is set.
       */
      public boolean hasFileData() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.com.microservice.hub.FileData fileData = 2;</code>
       * @return The fileData.
       */
      public com.microservice.hub.Bank.FileData getFileData() {
        if (fileDataBuilder_ == null) {
          return fileData_ == null ? com.microservice.hub.Bank.FileData.getDefaultInstance() : fileData_;
        } else {
          return fileDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.microservice.hub.FileData fileData = 2;</code>
       */
      public Builder setFileData(com.microservice.hub.Bank.FileData value) {
        if (fileDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fileData_ = value;
        } else {
          fileDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.microservice.hub.FileData fileData = 2;</code>
       */
      public Builder setFileData(
          com.microservice.hub.Bank.FileData.Builder builderForValue) {
        if (fileDataBuilder_ == null) {
          fileData_ = builderForValue.build();
        } else {
          fileDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.microservice.hub.FileData fileData = 2;</code>
       */
      public Builder mergeFileData(com.microservice.hub.Bank.FileData value) {
        if (fileDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            fileData_ != null &&
            fileData_ != com.microservice.hub.Bank.FileData.getDefaultInstance()) {
            getFileDataBuilder().mergeFrom(value);
          } else {
            fileData_ = value;
          }
        } else {
          fileDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.microservice.hub.FileData fileData = 2;</code>
       */
      public Builder clearFileData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileData_ = null;
        if (fileDataBuilder_ != null) {
          fileDataBuilder_.dispose();
          fileDataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.microservice.hub.FileData fileData = 2;</code>
       */
      public com.microservice.hub.Bank.FileData.Builder getFileDataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFileDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.microservice.hub.FileData fileData = 2;</code>
       */
      public com.microservice.hub.Bank.FileDataOrBuilder getFileDataOrBuilder() {
        if (fileDataBuilder_ != null) {
          return fileDataBuilder_.getMessageOrBuilder();
        } else {
          return fileData_ == null ?
              com.microservice.hub.Bank.FileData.getDefaultInstance() : fileData_;
        }
      }
      /**
       * <code>.com.microservice.hub.FileData fileData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.microservice.hub.Bank.FileData, com.microservice.hub.Bank.FileData.Builder, com.microservice.hub.Bank.FileDataOrBuilder> 
          getFileDataFieldBuilder() {
        if (fileDataBuilder_ == null) {
          fileDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.microservice.hub.Bank.FileData, com.microservice.hub.Bank.FileData.Builder, com.microservice.hub.Bank.FileDataOrBuilder>(
                  getFileData(),
                  getParentForChildren(),
                  isClean());
          fileData_ = null;
        }
        return fileDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.microservice.hub.PushFileRequest)
    }

    // @@protoc_insertion_point(class_scope:com.microservice.hub.PushFileRequest)
    private static final com.microservice.hub.Bank.PushFileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microservice.hub.Bank.PushFileRequest();
    }

    public static com.microservice.hub.Bank.PushFileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushFileRequest>
        PARSER = new com.google.protobuf.AbstractParser<PushFileRequest>() {
      @java.lang.Override
      public PushFileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PushFileRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PushFileRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.microservice.hub.Bank.PushFileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegisterBankRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.microservice.hub.RegisterBankRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
     * @return Whether the bankInfo field is set.
     */
    boolean hasBankInfo();
    /**
     * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
     * @return The bankInfo.
     */
    com.microservice.hub.Bank.BankInfo getBankInfo();
    /**
     * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
     */
    com.microservice.hub.Bank.BankInfoOrBuilder getBankInfoOrBuilder();
  }
  /**
   * Protobuf type {@code com.microservice.hub.RegisterBankRequest}
   */
  public static final class RegisterBankRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.microservice.hub.RegisterBankRequest)
      RegisterBankRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegisterBankRequest.newBuilder() to construct.
    private RegisterBankRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisterBankRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegisterBankRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservice.hub.Bank.internal_static_com_microservice_hub_RegisterBankRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservice.hub.Bank.internal_static_com_microservice_hub_RegisterBankRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservice.hub.Bank.RegisterBankRequest.class, com.microservice.hub.Bank.RegisterBankRequest.Builder.class);
    }

    public static final int BANKINFO_FIELD_NUMBER = 1;
    private com.microservice.hub.Bank.BankInfo bankInfo_;
    /**
     * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
     * @return Whether the bankInfo field is set.
     */
    @java.lang.Override
    public boolean hasBankInfo() {
      return bankInfo_ != null;
    }
    /**
     * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
     * @return The bankInfo.
     */
    @java.lang.Override
    public com.microservice.hub.Bank.BankInfo getBankInfo() {
      return bankInfo_ == null ? com.microservice.hub.Bank.BankInfo.getDefaultInstance() : bankInfo_;
    }
    /**
     * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
     */
    @java.lang.Override
    public com.microservice.hub.Bank.BankInfoOrBuilder getBankInfoOrBuilder() {
      return bankInfo_ == null ? com.microservice.hub.Bank.BankInfo.getDefaultInstance() : bankInfo_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bankInfo_ != null) {
        output.writeMessage(1, getBankInfo());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bankInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBankInfo());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microservice.hub.Bank.RegisterBankRequest)) {
        return super.equals(obj);
      }
      com.microservice.hub.Bank.RegisterBankRequest other = (com.microservice.hub.Bank.RegisterBankRequest) obj;

      if (hasBankInfo() != other.hasBankInfo()) return false;
      if (hasBankInfo()) {
        if (!getBankInfo()
            .equals(other.getBankInfo())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBankInfo()) {
        hash = (37 * hash) + BANKINFO_FIELD_NUMBER;
        hash = (53 * hash) + getBankInfo().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microservice.hub.Bank.RegisterBankRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.RegisterBankRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.RegisterBankRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.RegisterBankRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.RegisterBankRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservice.hub.Bank.RegisterBankRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservice.hub.Bank.RegisterBankRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservice.hub.Bank.RegisterBankRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.microservice.hub.Bank.RegisterBankRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.microservice.hub.Bank.RegisterBankRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microservice.hub.Bank.RegisterBankRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservice.hub.Bank.RegisterBankRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microservice.hub.Bank.RegisterBankRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.microservice.hub.RegisterBankRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.microservice.hub.RegisterBankRequest)
        com.microservice.hub.Bank.RegisterBankRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_RegisterBankRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_RegisterBankRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microservice.hub.Bank.RegisterBankRequest.class, com.microservice.hub.Bank.RegisterBankRequest.Builder.class);
      }

      // Construct using com.microservice.hub.Bank.RegisterBankRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bankInfo_ = null;
        if (bankInfoBuilder_ != null) {
          bankInfoBuilder_.dispose();
          bankInfoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microservice.hub.Bank.internal_static_com_microservice_hub_RegisterBankRequest_descriptor;
      }

      @java.lang.Override
      public com.microservice.hub.Bank.RegisterBankRequest getDefaultInstanceForType() {
        return com.microservice.hub.Bank.RegisterBankRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.microservice.hub.Bank.RegisterBankRequest build() {
        com.microservice.hub.Bank.RegisterBankRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.microservice.hub.Bank.RegisterBankRequest buildPartial() {
        com.microservice.hub.Bank.RegisterBankRequest result = new com.microservice.hub.Bank.RegisterBankRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.microservice.hub.Bank.RegisterBankRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bankInfo_ = bankInfoBuilder_ == null
              ? bankInfo_
              : bankInfoBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microservice.hub.Bank.RegisterBankRequest) {
          return mergeFrom((com.microservice.hub.Bank.RegisterBankRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microservice.hub.Bank.RegisterBankRequest other) {
        if (other == com.microservice.hub.Bank.RegisterBankRequest.getDefaultInstance()) return this;
        if (other.hasBankInfo()) {
          mergeBankInfo(other.getBankInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getBankInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.microservice.hub.Bank.BankInfo bankInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.microservice.hub.Bank.BankInfo, com.microservice.hub.Bank.BankInfo.Builder, com.microservice.hub.Bank.BankInfoOrBuilder> bankInfoBuilder_;
      /**
       * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
       * @return Whether the bankInfo field is set.
       */
      public boolean hasBankInfo() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
       * @return The bankInfo.
       */
      public com.microservice.hub.Bank.BankInfo getBankInfo() {
        if (bankInfoBuilder_ == null) {
          return bankInfo_ == null ? com.microservice.hub.Bank.BankInfo.getDefaultInstance() : bankInfo_;
        } else {
          return bankInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
       */
      public Builder setBankInfo(com.microservice.hub.Bank.BankInfo value) {
        if (bankInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bankInfo_ = value;
        } else {
          bankInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
       */
      public Builder setBankInfo(
          com.microservice.hub.Bank.BankInfo.Builder builderForValue) {
        if (bankInfoBuilder_ == null) {
          bankInfo_ = builderForValue.build();
        } else {
          bankInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
       */
      public Builder mergeBankInfo(com.microservice.hub.Bank.BankInfo value) {
        if (bankInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            bankInfo_ != null &&
            bankInfo_ != com.microservice.hub.Bank.BankInfo.getDefaultInstance()) {
            getBankInfoBuilder().mergeFrom(value);
          } else {
            bankInfo_ = value;
          }
        } else {
          bankInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
       */
      public Builder clearBankInfo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bankInfo_ = null;
        if (bankInfoBuilder_ != null) {
          bankInfoBuilder_.dispose();
          bankInfoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
       */
      public com.microservice.hub.Bank.BankInfo.Builder getBankInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBankInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
       */
      public com.microservice.hub.Bank.BankInfoOrBuilder getBankInfoOrBuilder() {
        if (bankInfoBuilder_ != null) {
          return bankInfoBuilder_.getMessageOrBuilder();
        } else {
          return bankInfo_ == null ?
              com.microservice.hub.Bank.BankInfo.getDefaultInstance() : bankInfo_;
        }
      }
      /**
       * <code>.com.microservice.hub.BankInfo bankInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.microservice.hub.Bank.BankInfo, com.microservice.hub.Bank.BankInfo.Builder, com.microservice.hub.Bank.BankInfoOrBuilder> 
          getBankInfoFieldBuilder() {
        if (bankInfoBuilder_ == null) {
          bankInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.microservice.hub.Bank.BankInfo, com.microservice.hub.Bank.BankInfo.Builder, com.microservice.hub.Bank.BankInfoOrBuilder>(
                  getBankInfo(),
                  getParentForChildren(),
                  isClean());
          bankInfo_ = null;
        }
        return bankInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.microservice.hub.RegisterBankRequest)
    }

    // @@protoc_insertion_point(class_scope:com.microservice.hub.RegisterBankRequest)
    private static final com.microservice.hub.Bank.RegisterBankRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microservice.hub.Bank.RegisterBankRequest();
    }

    public static com.microservice.hub.Bank.RegisterBankRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterBankRequest>
        PARSER = new com.google.protobuf.AbstractParser<RegisterBankRequest>() {
      @java.lang.Override
      public RegisterBankRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RegisterBankRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterBankRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.microservice.hub.Bank.RegisterBankRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_microservice_hub_FileData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_microservice_hub_FileData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_microservice_hub_BankInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_microservice_hub_BankInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_microservice_hub_PushFileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_microservice_hub_PushFileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_microservice_hub_RegisterBankRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_microservice_hub_RegisterBankRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbank.proto\022\024com.microservice.hub\"1\n\010Fi" +
      "leData\022\020\n\010fileName\030\001 \001(\t\022\023\n\013fileContent\030" +
      "\002 \001(\014\"B\n\010BankInfo\022\016\n\006bankId\030\001 \001(\t\022\024\n\014ban" +
      "kHostname\030\002 \001(\t\022\020\n\010bankPort\030\003 \001(\005\"S\n\017Pus" +
      "hFileRequest\022\016\n\006bankId\030\001 \001(\t\0220\n\010fileData" +
      "\030\002 \001(\0132\036.com.microservice.hub.FileData\"G" +
      "\n\023RegisterBankRequest\0220\n\010bankInfo\030\001 \001(\0132" +
      "\036.com.microservice.hub.BankInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_microservice_hub_FileData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_microservice_hub_FileData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_microservice_hub_FileData_descriptor,
        new java.lang.String[] { "FileName", "FileContent", });
    internal_static_com_microservice_hub_BankInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_microservice_hub_BankInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_microservice_hub_BankInfo_descriptor,
        new java.lang.String[] { "BankId", "BankHostname", "BankPort", });
    internal_static_com_microservice_hub_PushFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_microservice_hub_PushFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_microservice_hub_PushFileRequest_descriptor,
        new java.lang.String[] { "BankId", "FileData", });
    internal_static_com_microservice_hub_RegisterBankRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_microservice_hub_RegisterBankRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_microservice_hub_RegisterBankRequest_descriptor,
        new java.lang.String[] { "BankInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
